baseURL = 'https://mjmrozek.com/'
title = 'Matthäus Mrozek'
theme = 'PaperMod'

# Definiere Standard-Sprache
defaultContentLanguage = "en" # Standardmäßig Englisch
defaultContentLanguageInSubdir = true # Platzierung der Standard-Sprache in einem Unterordner

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    weight = 1
    languageCode = "en-us"
    title = "Matthäus Mrozek"
  
  [languages.de]
    languageName = "Deutsch"
    contentDir = "content/deutsch"
    weight = 2
    languageCode = "de-de"
    title = "Matthäus Mrozek"

[params]
  showPostNavLinks = true
  comments = false
  showReadingTime = false
  showShareButtons = true
  showBreadCrumbs = true
  disableThemeToggle = false
  mainSections = ["posts"]
  defaultTheme = "light" # Erzwingt das helle Theme als Standard




# Globale Parameter für Englisch
[params.homeInfoParams]
  Title = "Blogging & IT Solutions"
  Content = """
  **Classification of the website**  
  This website is a hub […] with [me] as a person in an immutable center, seemingly chaotically 
  amalgamating various areas of life, or fields, within itself. [Read more...](/en/posts/2022-12-22/)


</br></br>  


"""

# Spezifische Parameter für Deutsch
[languages.de.params.homeInfoParams]
  Title = "Blogging & IT-Solutions"
  Content = """

  
  **Einordnung der Webseite**  
  Diese Webseite ist ein Knotenpunkt […] mit [mir] als Person im unveränderlichen Zentrum, die nur scheinbar chaotisch 
  unterschiedlichste Lebensbereiche, bzw. Gebiete oder Felder in sich vereint. [Mehr erfahren...](/de/posts/2022-12-22/)  



</br></br>  


  """


# Social Icons bleiben gleich, da sie sprachunabhängig sind
[[params.socialIcons]]
# ... (deine vorhandenen Social-Icons)
  [[params.socialIcons]]
  name = "email"
  url = "mailto:mjmrozek@gmail.com"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/mjmrozek"

  [[params.socialIcons]]
  name = "threads"
  url = "https://www.threads.net/@mjmrozek"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mjmrozek/"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/matthaeusjmrozek"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/mjmrozek/"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@mjmrozek"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/mjmrozek"



# Menüeinträge für Englisch
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 4

[[menu.main]]
name = "Business"
url = "/business/"
weight = 5

[[menu.main]]
name = "About"
url = "/about/"
weight = 6

[[menu.main]]
name = "Legal"
url = "/legal/"
weight = 7

[[menu.main]]
name = "Archives"
url = "/en/archives/"  # Angepasst an das Sprachen-Kürzel
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

# Menüeinträge für Deutsch
[[languages.de.menu.main]]
name = "Blog"
url = "/de/posts/"
weight = 1

[[languages.de.menu.main]]
name = "Portfolio"
url = "/de/portfolio/"
weight = 4

[[languages.de.menu.main]]
name = "Business"
url = "/de/business/"
weight = 5

[[languages.de.menu.main]]
name = "Über mich"
url = "/de/about/"
weight = 6

[[languages.de.menu.main]]
name = "Rechtliches"
url = "/de/legal/"
weight = 7

[[languages.de.menu.main]]
name = "Archiv"
url = "/de/archives/"  # Angepasst an das Sprachen-Kürzel
weight = 2

[[languages.de.menu.main]]
name = "Tags"
url = "/de/tags/"
weight = 3
