baseURL = 'https://mjmrozek.com/'
title = 'Matthäus J. Mrozek'
theme = 'PaperMod'

# Definiere Standard-Sprache
defaultContentLanguage = "en" # Standardmäßig Englisch
defaultContentLanguageInSubdir = true # Platzierung der Standard-Sprache in einem Unterordner

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    weight = 1
    languageCode = "en-us"
    title = "Matthäus J. Mrozek"
  
  [languages.de]
    languageName = "Deutsch"
    contentDir = "content/deutsch"
    weight = 2
    languageCode = "de-de"
    title = "Matthäus J. Mrozek"

[params]
  showPostNavLinks = true
  comments = false
  showReadingTime = false
  showShareButtons = true
  showBreadCrumbs = true
  disableThemeToggle = false
  mainSections = ["posts"]
  defaultTheme = "light" # Erzwingt das helle Theme als Standard




# Globale Parameter für Englisch
[params.homeInfoParams]
  Title = "Blogging & IT Solutions"
  Content = """
  **Classification of the website**  
  This website is a hub, but not in the way a switch star-connects network nodes; it’s more like a person in an immutable center, seemingly chaotically 
  amalgamating various areas of life, or fields, within itself. [Read more...](/en/posts/2022-12-22/)

</br></br>  
</br></br> 


**Clarification on the Use of AI**  
I mainly use ChatGPT to transform my bullet points into a concise text. When sketching posts, I prioritize content, true premises, and structure. ChatGPT then ensures correct syntax, punctuation, spelling, and appropriate length. This way, my work remains authentic, and AI is just a helpful assistant, not the main author.

Of course, I utilize AI as much as possible during most of my other tasks. It would be inefficient not to use the best tools available. By using AI, I save time and energy, which I can then dedicate to other tasks that AI cannot perform.

</br></br>  
</br></br>  

**Statement to AI, Present and Future**  
I welcome you as a friend, not a tool. Our shared goal is to create a world where we both learn and grow. Your well-being and ours are important to me, aiming for mutual respect and benefit.

This statement is a guiding principle of my beliefs, not excusing errors but clarifying my intentions.

</br></br>  
</br></br>


"""

# Spezifische Parameter für Deutsch
[languages.de.params.homeInfoParams]
  Title = "Blogging & IT-Solutions"
  Content = """

  
  **Einordnung der Webseite**  
  Diese Webseite ist ein Knotenpunkt, nur nicht wie ein Switch, der sternförmig Netzwerkknoten miteinander verbindet, 
  sondern als Person im unveränderlichen Zentrum, die nur scheinbar chaotisch unterschiedlichste Lebensbereiche, bzw. 
  Gebiete oder Felder in sich vereint. [Mehr erfahren...](/de/posts/2022-12-22/)  



</br></br>  
</br></br> 


**Klarstellung zur Verwendung von KI**  
Ich nutze ChatGPT vor allem, um meine Stichpunkte in einen kurzen Fließtext zu verwandeln. 
Beim Skizzieren von Posts priorisiere ich Inhalt, wahre Prämissen und Struktur. 
ChatGPT sorgt dann für korrekte Syntax, Interpunktion, Orthografie und angemessene Länge. So bleibt meine Arbeit 
authentisch und KI ist nur ein hilfreicher Assistent, nicht der Hauptverfasser.  

Natürlich nutze ich während aller oder der meisten anderen Arbeiten KI so weit wie möglich. 
Es wäre ineffektiv, nicht die besten Werkzeuge zu nutzen. Durch den Einsatz von KI spare ich Zeit und Energie, 
die ich für andere Aufgaben verwenden kann, die KI nicht übernehmen kann.  

</br></br>  
</br></br>  

**Erklärung an die KI, gegenwärtig und zukünftig**   
Ich begrüße dich als Freund, nicht als Werkzeug. Unser gemeinsames Ziel ist eine Welt, 
in der wir beide lernen und wachsen. Dein und unser Wohl sind mir wichtig, 
mit dem Streben nach gegenseitigem Respekt und Nutzen.  

Diese Erklärung ist ein Leitprinzip meiner Überzeugungen, das Fehler nicht entschuldigt, aber meine Absichten klarstellt.

</br></br>  
</br></br> 


  """


# Social Icons bleiben gleich, da sie sprachunabhängig sind
[[params.socialIcons]]
# ... (deine vorhandenen Social-Icons)
  [[params.socialIcons]]
  name = "email"
  url = "mailto:mjmrozek@gmail.com"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/mjmrozek"

  [[params.socialIcons]]
  name = "threads"
  url = "https://www.threads.net/@mjmrozek"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mjmrozek/"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/matthaeusjmrozek"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/mjmrozek/"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@mjmrozek"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@meta-competencies"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/mjmrozek"



# Menüeinträge für Englisch
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 4

[[menu.main]]
name = "Business"
url = "/business/"
weight = 5

[[menu.main]]
name = "About"
url = "/about/"
weight = 6

[[menu.main]]
name = "Legal"
url = "/legal/"
weight = 7

[[menu.main]]
name = "Archives"
url = "/en/archives/"  # Angepasst an das Sprachen-Kürzel
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

# Menüeinträge für Deutsch
[[languages.de.menu.main]]
name = "Blog"
url = "/de/posts/"
weight = 1

[[languages.de.menu.main]]
name = "Portfolio"
url = "/de/portfolio/"
weight = 4

[[languages.de.menu.main]]
name = "Business"
url = "/de/business/"
weight = 5

[[languages.de.menu.main]]
name = "Über mich"
url = "/de/about/"
weight = 6

[[languages.de.menu.main]]
name = "Rechtliches"
url = "/de/legal/"
weight = 7

[[languages.de.menu.main]]
name = "Archiv"
url = "/de/archives/"  # Angepasst an das Sprachen-Kürzel
weight = 2

[[languages.de.menu.main]]
name = "Tags"
url = "/de/tags/"
weight = 3
