baseURL = 'https://mjmrozek.com/'
title = 'Matthäus Mrozek'
theme = 'PaperMod'

# Definiere Standard-Sprache
defaultContentLanguage = "en" # Standardmäßig Englisch
defaultContentLanguageInSubdir = true # Platzierung der Standard-Sprache in einem Unterordner

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    weight = 1
    languageCode = "en-us"
    title = "Matthäus Mrozek"
  
  [languages.de]
    languageName = "Deutsch"
    contentDir = "content/deutsch"
    weight = 2
    languageCode = "de-de"
    title = "Matthäus Mrozek"

[params]
  showPostNavLinks = true
  comments = false
  showReadingTime = false
  showShareButtons = true
  showBreadCrumbs = true
  disableThemeToggle = false
  mainSections = ["posts"]
  defaultTheme = "light" # Erzwingt das helle Theme als Standard




# Globale Parameter für Englisch
[params.homeInfoParams]
  Title = "Blogging & IT Solutions"
  Content = """
  **Classification**  
  This website is a hub [...] with [me] as a person in an immutable center [[...]](/en/posts/2022-12-22/)

</br>

  **Update Note**  
  This site is rarely maintained – see social media.

  </br>

**Recent Projects**  
[LMC – Learning Platform for Meta Competencies](https://mjmrozek.notion.site/LMC-Learning-Platform-for-Meta-Competencies-Documentation-2ad589215ffb4924afd68654063e9403?source=copy_link)
</br></br>  




"""

# Spezifische Parameter für Deutsch
[languages.de.params.homeInfoParams]
  Title = "Blogging & IT-Solutions"
  Content = """

  
  **Einordnung**  
  Diese Webseite ist ein Knotenpunkt […] mit [mir] als Person im unveränderlichen Zentrum [[...]](/de/posts/2022-12-22/)  

</br>

  **Hinweis zur Aktualität**  
  Diese Seite wird selten gepflegt – siehe Social Media.

  </br>


  **Letzte Projekte**  
  [LMC – Learning Platform fpr Meta Competencies](https://mjmrozek.notion.site/LMC-Learning-Platform-for-Meta-Competencies-Documentation-2ad589215ffb4924afd68654063e9403?source=copy_link)


</br></br>  


  """


# Social Icons bleiben gleich, da sie sprachunabhängig sind
[[params.socialIcons]]
# ... (deine vorhandenen Social-Icons)
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/mjmrozek"

[[params.socialIcons]]
name = "threads"
url = "https://www.threads.net/@mjmrozek"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/mjmrozek/"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@mjmrozek"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/mjmrozek/"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/matthaeusjmrozek"

[[params.socialIcons]]
name = "github"
url = "https://github.com/mjmrozek"

[[params.socialIcons]]
name = "email"
url = "mailto:mjmrozek@gmail.com"



# Menüeinträge für Englisch
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 4

[[menu.main]]
name = "Business"
url = "/business/"
weight = 5

[[menu.main]]
name = "About"
url = "/about/"
weight = 6

[[menu.main]]
name = "Legal"
url = "/legal/"
weight = 7

[[menu.main]]
name = "Archives"
url = "/en/archives/"  # Angepasst an das Sprachen-Kürzel
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

# Menüeinträge für Deutsch
[[languages.de.menu.main]]
name = "Blog"
url = "/de/posts/"
weight = 1

[[languages.de.menu.main]]
name = "Portfolio"
url = "/de/portfolio/"
weight = 4

[[languages.de.menu.main]]
name = "Business"
url = "/de/business/"
weight = 5

[[languages.de.menu.main]]
name = "Über mich"
url = "/de/about/"
weight = 6

[[languages.de.menu.main]]
name = "Rechtliches"
url = "/de/legal/"
weight = 7

[[languages.de.menu.main]]
name = "Archiv"
url = "/de/archives/"  # Angepasst an das Sprachen-Kürzel
weight = 2

[[languages.de.menu.main]]
name = "Tags"
url = "/de/tags/"
weight = 3
